# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  #  secret_key: "58121753ea46227927527a9e60cb93747bd31873c122515486270cac5dcd87fd"  # change this!
  secret_key: " 549e64a7cc9900a1522bbaff6ba08f8ffae8f46b3a0917266c67a0db8eb601ee"
  limiter: true  # can be disabled for a private instance
  image_proxy: true
  public_instance: true
  method: "GET"
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
general:
  # Debug mode, only for development. Is overwritten by ${SEARXNG_DEBUG}
  debug: false
  # displayed name
  instance_name: "Cynay - People's Search Engine"
  # mailto:contact@example.com
  contact_url: false
  # record stats
  enable_metrics: true
brand:
  new_issue_url: https://cynay.com
  docs_url: https://cynay.com
  public_instances: https://cynay.com
  wiki_url: https://cynay.com
  issue_url: https://cynay.com
search:
  # Filter results. 0: None, 1: Moderate, 2: Strict
  safe_search: 2
  autocomplete: ""
  # minimun characters to type before autocompleter starts
  autocomplete_min: 2
outgoing:
  pool_connections: 100000      # Maximum number of allowable connections, or null
                             # for no limits. The default is 100.
  pool_maxsize: 10000           # Number of allowable keep-alive connections, or null
                             # to always allow. The default is 10
